name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Saturnus
      run: cargo install --git https://github.com/sigmasoldi3r/Saturnus.git saturnus
    - name: Run the compiler
      run: |
       saturnus -c commander.saturn
       saturnus -c enquirer.saturn
       saturnus -c grabby.saturn
       saturnus -c lark.saturn
       saturnus -c lyre.saturn
       saturnus -c monody.saturn
       saturnus -c netpipe.saturn
       saturnus -c robot.saturn
    - name: Publish the artifacts
      run: |
        curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.gist_deploy_key }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/gists/5a71c8a4343a0736236b49c81a80d495 \
          -d '{"files":{"commander.lua":{"content":"$(cat commander.lua)"}}}'
