name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Saturnus
      run: cargo install --git https://github.com/sigmasoldi3r/Saturnus.git saturnus
    - name: Run the compiler
      run: |
       saturnus -c commander.saturn
       saturnus -c enquirer.saturn
       saturnus -c grabby.saturn
       saturnus -c lark.saturn
       saturnus -c lyre.saturn
       saturnus -c monody.saturn
       saturnus -c netpipe.saturn
       saturnus -c robot.saturn
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Publish the artifacts
      env:
        GIST_DEPLOY_KEY: ${{ secrets.GIST_DEPLOY_KEY }}
      run: |
        deno run --allow-net=* --allow-read --allow-env .github/deploy/deploy.js
